### ISSUE TITLE
Glossary - write/publish guidelines

### ISSUE THREAD

**Issue by maxder** [maxder/content#10]
- [ ] Review Glossary guideline (COR)
- [ ] Review, fix, format, cleanup existing terms/faqs in SharePoint per guidelines.
- [ ] Guide to build http://data.providence.org/sites/hi/HIOM/Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fhi%2FHIOM%2FDocuments%2F%5FManuals%2FContent%20Standard

**Comment by Mr-Disco** [comment]
Guidelines to  convert into standards http://data.providence.org/sites/hi/HIOM/OneNote%20Library/Ontology%20Manual/myHIway.one#section-id={781DFAF5-D9A1-49DB-951C-8DDB8795027A}&end

**Comment by Mr-Disco** [comment]
Purpose
The intent of the myHIway Glossary is to provide a single, consistent resource for definitions that pertain to  enterprise business, data, and processes. By including organizational specific usage and nuance, this glossary serves as the basis for enterprise training materials, business process definition, system help documentation, and other resources.

Checklist
Syntax
	• The definition contains the term, its class and attributes that distinguish the term from other members of the class, for example; "An antidepressant is a type of drug that is used to treat psychological depression."

Composition
	• Synonyms or antonyms are used where helpful.
	
	• Hyphenation is used appropriately to make meanings clear.
	
	• The definition avoids situational phrases like: 
		• is when 
		• is where 
		• is used to 
		• describes a situation in which 
	
	• The definition uses purposeful phrases like:
		• that 
		• consists of
		• is made up of 
		• is concerned with

Audience
	• The definition is meaningful to the target audience, which is an enterprise employee with basic company knowledge.

	• All terms used in the definition are also defined, unless well understood. 

Circular reference
	• The definition does not use the term being defined in the definition itself.

Context
	• If the term has different meanings within the context of the enterprise, each context and related definition is provided.

Source
	• The term is written in your own words (unless copy permission was granted)
	
	• Any additional information to make the term enterprise specific has been added 
	
	• General industry definitions, if relevant, are properly referenced if the definition was copied
