### ISSUE TITLE
LogicStream - Import Data

### ISSUE THREAD

**Issue by maxder** [maxder/content#11]
#### **Discovery**
- [x] Meeting w/ Thom, Kathy, Katy, Max
- [x] Get login access
- [x] Get info about web server

#### **SharePoint Data**
- [x] Create DataCatalog-Products_LogicStream
  * Type of Report - LogicStream_View
  * Reporting Environment - LogicStream
  * Source Application
  * Report to Report Associations -> Tableau Reports
- [x] DataCatalog-Filters
  * Add Type of Report -> ???
  * Add Reporting Environment  -> LogicStream
- [ ] DataCatalog-Topics -> ??? (Clinical Informatics/Clinical Decision Support/LogicStream)
- [ ] Add Katy w/ CRUD permissions
- [x] Add initial list items

**Comment by maxder** [comment]
Components is the home page
Component Type - mapped to an Epic term (see FAQ)
Ordered by EHR Activity
Smart Phrase 
EHR User activity - not Patient or Encounter level data
Order sets - orders, cancellations, stats
Behavior of EHR users, status
No Timestamps - 
Populations - types of orders, hypothermic order set usage across population or diagnostic code
CAUTI - alert fires on 14th day, 

Sitting on Clarity tables - pulls data every night

Reports - 
500 active users - 200 online

Order activity by caregiver

Training
Access to Logicstream
Path to generic page
Help desk

Manual list (10-20)
Related reports from Tableau

Clinical Informatics
Clinical Decision Support

**Comment by Mr-Disco** [comment]
- [ ] SharePoint List: http://data.providence.org/sites/hi/HIOM/Lists/DataCatalogProducts_Reports_LogicStream/FusionSearch.aspx

- [ ] Thom has access
