### ISSUE TITLE
Platform Overviews

### ISSUE THREAD

**Issue by maxder** [maxder/content#15]
#### Vantage Info
- [ ] Overview/backstory
- [ ] How to get access
- [ ] FAQs
- [ ] Who to contact
- [ ] How to get training/demo
- [ ] Who uses the platform
- [ ] About page

#### Insights Info
- [ ] Overview/backstory
- [ ] How to get access
- [ ] FAQs
- [ ] Blogs
- [ ] Who to contact
- [ ] How to get training/demo
- [ ] Who uses the platform (1200 member user group)

#### LogicStream Info
- [ ] Overview/backstory
- [ ] How to get access
- [ ] FAQs
- [ ] Who to contact
- [ ] How to get training/demo
- [ ] Who uses the platform (500 member user group)

**Comment by Mr-Disco** [comment]
What does the final product for these overviews look like? Word Document? OneNote?
