### ISSUE TITLE
MySQL - setup for user feedback monitoring

### ISSUE THREAD

**Issue by maxder** [maxder/content#2]
- [x] create Excel/MySQL connection
- [x] configure sync, annotations, database
- [x] document setup
- [ ] train & deploy Kathy/Patricia

**Comment by Mr-Disco** [comment]
- [ ] Excel document created. http://data.providence.org/sites/hi/HIOM/Documents/Reporting/Comments%20Like%20and%20Favorites%20Report.xlsx
- [ ] Posted first page to Excel Webpart on Reporting page
http://data.providence.org/sites/hi/HIOM/Pages/Reporting.aspx
- [ ] Data is pulled from mySQL, and pasted into Request list for reporting and tracking of comments
http://data.providence.org/sites/hi/HIOM/Lists/myHIway_Requests/TwigKit_CLF.aspx
