### ISSUE TITLE
Customer Facing Documentation

### ISSUE THREAD

**Issue by maxder** [maxder/content#3]
#### Data Catalog Modeling Standards
- [x] Develop
- [x] Convert to PDF
- [x] Post to DPO
#### Data Catalog Metadata Standards
- [x] Develop
- [x] Convert to PDF
- [x] Post to DPO
#### Data Catalog Customer Fulfillment Checklist
- [x] Develop
- [x] Convert to PDF
- [x] Post to DPO
#### Data Catalog Customer Fulfillment Process
- [x] Develop
- [x] Convert to PDF
- [x] Post to DPO

**Comment by maxder** [comment]
_From @Mr-Disco on March 2, 2017 15:23_

fromal documentation complete. working intake list to match checklist.

**Comment by Mr-Disco** [comment]
Completed Training documents on DPO and Request list info link on the form.
