### ISSUE TITLE
ACO Metrics - review

### ISSUE THREAD

**Issue by maxder** [maxder/content#4]
#### Review the [DataCatalog_Products_Metrics_ACO SharePoint list](http://data.providence.org/sites/hi/HIOM/Lists/DataCatalogProducts_Metrics_ACO/Enter%20Products.aspx)
- [x] Type of Metric ?

#### Review the [DataCatalog_Products_Reports_ACO SharePoint list](http://data.providence.org/sites/hi/HIOM/Lists/DataCatalogProducts_Reports_ACO/Enter%20Products.aspx)
- [x] Add Accountable Care Orginzation asTopics

#### Add ACO to Topics
- [ ] Suggest adding under Business Operations >  > ACO
- [ ] Ask Brook what "Topic" could it fit under? http://hi.providence.org/myhiway/

**Comment by Mr-Disco** [comment]
ACO Topic drop down needs to be defined better. - need image

**Comment by Mr-Disco** [comment]
Sent follow-up email on 3/28

**Comment by Mr-Disco** [comment]
4/5 meeting with Brooke, suggested layout of Topics Menu
1.	Population Health
	a.	Accountable Care Services
		i.	Accountable Care Organization
	b.	Physician Services (PEPN)
		i.	Express Care
		ii.	Physician Services
	c.	Payer Contracting
		i.	Government Programs

- http://in.providence.org/sss/departments/pophealth/Pages/default.aspx

- Build to emulate this page: http://in.providence.org/sss/departments/acs/Pages/DataAnalytics.aspx

**Comment by Mr-Disco** [comment]
Added Kathy. Work with Micheal Westover, Micheal Meldahl, Tom French, Andrew Ibrahim, Amy Brittan
